---
- name: Install Apache and PHP
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ apache_php_packages }}"

- name: Ensure Apache is running and enabled
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: Configure Apache for WordPress
  template:
    src: wordpress.conf.j2
    dest: "/etc/apache2/sites-available/{{ wordpress_conf_file }}"
  notify: restart apache

- name: Enable WordPress site
  command: "a2ensite {{ wordpress_conf_file }}"
  when: ansible_os_family == 'Debian'
  notify: restart apache

- name: Enable Apache modules
  command: "a2enmod {{ item }}"
  with_items: "{{ apache_modules }}"
  when: ansible_os_family == 'Debian'
  notify: restart apache