---
- name: Download WordPress
  get_url:
    url: "https://wordpress.org/latest.tar.gz"
    dest: /tmp/wordpress.tar.gz

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html/
    remote_src: yes

- name: Configure WordPress
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wordpress/wp-config.php

- name: Set permissions
  file:
    path: /var/www/html/wordpress
    owner: "{{ apache_user }}"
    group: "{{ apache_user }}"
    recurse: yes