Vagrant.configure("2") do |config|
  config.vm.define "dev" do |dev|
    dev.vm.box = "ubuntu/focal64"
    dev.vm.hostname = "dev"
    dev.vm.network "private_network", ip: "192.168.56.11"
  end

  config.vm.define "prod" do |prod|
    prod.vm.box = "ubuntu/focal64"
    prod.vm.hostname = "prod"
    prod.vm.network "private_network", ip: "192.168.56.12"
  end
end